### ISSUE TITLE
Treinamentos

### ISSUE THREAD

**Issue by Mylena-angelica** [fga-eps-mds/2022-2-Squad02#1]
## Issue para postar os treinamentos relacionados a disciplina de Métodos de Desenvolvimento de Software 2022.2.

Os treinamentos serão os seguintes:

- Métodos ágeis;
- Configuração de ambiente;
- Git;
- Github;
- Gitpage;
- Documentos ágeis;
- Documentação do projeto de software.

**Comment by Beatrizvn** [comment]
## Métodos ágeis

**Slide:**

[Métodos ágeis.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/9954451/Metodos.ageis.pdf)

**Leituras:**
1. [Scrum](https://medium.com/reprogramabr/scrum-um-breve-resumo-f051e1bc06d9#:~:text=M%C3%A9todo%20SCRUM%20%E2%80%94%20Um%20resumo%20de%20tudo%20o%20que%20voc%C3%AA%20precisa%20saber,-Voc%C3%AA%20j%C3%A1%20ouviu&text=TRANSPAR%C3%8ANCIA%20dos%20processos%2C%20dos%20requisitos,o%20que%20est%C3%A1%20sendo%20feito)
2. [XP (Extreme Programming)](https://medium.com/codengage/um-pouco-sobre-o-m%C3%A9todo-xp-ea2e6baae561)

**Comment by Mylena-angelica** [comment]
## Documentação ágil

**Slide:**

[Documentação ágil.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/9955724/Documentacao.agil.pdf)



**Leituras:**
1. [Documentos gerais- Github](https://support.github.com/)
2. [Documentos de pull request- Github](https://docs.github.com/pt/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
3. [Boas práticas- Pull requests](https://medium.com/devzera/pull-requests-f492ab93e7dd)
4. [6 boas práticas para documentação com desenvolvimento ágil de softwares](https://blog.cronapp.io/documentacao-com-desenvolvimento-agil-de-softwares/)

**Comment by ananorberto** [comment]
## GitHub

**Slide:**

[GitHub.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/9963553/GitHub.pdf)

**Leituras:**

1. [Issues](https://alyssonmach.github.io/Minicurso-Git-e-GitHub/jup-not/IssueFork.html)
2. [Documentação](https://docs.pipz.com/central-de-ajuda/learning-center/guia-basico-de-markdown#open)
3. Pull Request [site](https://coodesh.com/blog/dicionario/o-que-e-pull-request-pr/) / [video](https://www.youtube.com/watch?v=U-Y_Mtdyo74)
4. [Branches](https://docs.github.com/pt/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches)

**Comment by ananorberto** [comment]
## Gitpage

#### Temas / estruturas a serem reaproveitadas:

- [Lino, o Bot](https://botlino.github.io/docs/)
- [Ludum](https://fga-eps-mds.github.io/2019.1-Ludum/#/)
- [CherryUp](https://fga-eps-mds.github.io/2020.2-CheeryUP/#/)
- [EuPescador](https://fga-eps-mds.github.io/2022-1-EuPescador-Doc/)

**Comment by anafernanndess** [comment]
### GIT
**Slide:** 
[GIT.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/9974583/GIT.pdf)

**Leituras:**

1. https://docs.github.com/pt/get-started/using-git/about-git
2. https://blog.betrybe.com/git/
3. https://www.youtube.com/watch?v=Zwv9qRyVeU4
4. https://www.udemy.com/course/git-e-github-para-iniciantes/

**Comment by TalesRG** [comment]
Configuração do Ambiente
Slide:
[Configuração do Ambiente.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/9976907/Configuracao.do.Ambiente.pdf)
Leituras:
https://docs.github.com/pt/get-started/getting-started-with-git/setting-your-username-in-git
https://www.oficinadanet.com.br/linux/24945-5-razoes-para-usar-o-linux-mint-em-vez-do-ubuntu
https://www.dz-techs.com/pt/linux-mint-vs-ubuntu-distro-choose

**Comment by Mylena-angelica** [comment]
> ## Gitpage
> 
> 
> 
> #### Temas / estruturas a serem reaproveitadas:
> 
> 
> 
> 1. [Lino, o Bot](https://botlino.github.io/docs/)
> 
> 2. [Ludum](https://fga-eps-mds.github.io/2019.1-Ludum/#/)
> 
> 3. [CherryUp](https://fga-eps-mds.github.io/2020.2-CheeryUP/#/)
> 
> 4. [EuPescador](https://fga-eps-mds.github.io/2022-1-EuPescador-Doc/)
> 
> 
> 
> 

A gitpage desse semestre será uma landing page do nosso produto.

**Comment by leonardogonmac** [comment]
### Documentação de Projeto de Software

PDF: 
[Documentação de projeto de software.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/9983588/Documentacao.de.projeto.de.software.pdf)

Links do material de referência:
- [Software Documentation Types and Best Practices](https://blog.prototypr.io/software-documentation-types-and-best-practices-1726ca595c7f)    (Documentação geral)
- [Best Practices in Code Documentation](https://santexgroup.com/blog/code-documentation-good-practices/)  (Documentação de código)
- [What Is A Design Doc In Software Engineering?](https://www.youtube.com/watch?v=bgHL41e7vgI) (Documentação de arquitetura)
- [Importance of Software Testing Documentation](https://pflb.us/blog/importance-of-software-testing-documentation/)  (Documentação de testes ou Quality Assurance)
