### ISSUE TITLE
SQL - tutorial para iniciantes

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#16]
#### Objetivo? 
Preparar um arquivo de estudos de SQL para treinamento do grupo.

#### Tarefas 
- [x] Documento de estudo para os outros membros do grupo.

#### Comentários

**Comment by manuziny** [comment]
Links usados para a pesquisa do [Tutorial SQL](https://github.com/fga-eps-mds/2022-2-Squad02/blob/main/TutorialSQL.md):
- [SQL: O que é e como usar os principais comandos básicos SQL](https://blog.betrybe.com/sql/);
- [Saiba tudo sobre SQL - A linguagem padrão para trabalhar com banco de dados relacionais!](https://www.alura.com.br/artigos/o-que-e-sql?gclid=Cj0KCQiAm5ycBhCXARIsAPldzoUQGku0mxGzvkvPrPGVvmtWpIsANRibNACVWSHFmD1-9CfHYRpatGoaAouwEALw_wcB);
- [Documentação do Microsoft SQL](https://learn.microsoft.com/pt-br/sql/?view=sql-server-ver16).
