### ISSUE TITLE
Issue 1 → Pesquisa de mercado

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#2]
#### O que? 
Pesquisar softwares com finalidade parecidas com o nosso Bot para enviar conteúdos para o Telegram.

#### Tarefas 
- [x] Pesquisar um ou mais projetos parecidos;
- [x] Fazer uma análise breve desses projetos e documentar para estudo dos outros membros da equipe.
----------
#### Comentários 
-----------

**Comment by Mylena-angelica** [comment]
Pesquisa de mercado: [https://mylena-angelica.notion.site/Sprint-1-Issue-1-f5287365da1a43119ad39ffc418608a4](Documento no notion)
