### ISSUE TITLE
Modelo lógico e conceitual do banco de dados

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#21]
#### Objetivo? 
Criar a modelagem de dados → uma técnica usada para a especificação das regras de negócios e as estruturas de dados de 
um banco de dados.

#### Qual o problema?
A modelagem de dados faz parte do ciclo de desenvolvimento de um sistema e é de vital importância para o bom resultado do projeto.

#### Tarefas 
- [x] Decidir qual SGBD será utilizado
- [x] Colocar nos comentários da issue a modelagem

#### Comentários 
---------------

**Comment by TalesRG** [comment]
O SGBD que vamos utilizar é o MYSQL: https://dev.mysql.com/doc/
Link para download do MYSQL: https://dev.mysql.com/downloads/mysql/
