### ISSUE TITLE
Organizar a estrutura do código + banco de dados

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#22]
#### Objetivo? 
Organizar como faremos a conexão do bot com o banco de dados.

#### Qual o problema?
Precisamos organizar como o banco de dados irá enviar os conteúdos e receber que o aluno finalizou o conteúdo.

#### Tarefas 
- [x] Como o bot vai interagir com o bancos de dados?
- [x] Como o aluno vai receber os conteúdos do bot?
- [x] Como ele vai marcar como concluído?
- [x] Temos como fazer uma etapa de verificação para ter certeza que o aluno concluiu o conteúdo?

#### Comentários 
---------------

**Comment by TalesRG** [comment]
![imagem_2022-12-07_195145136](https://user-images.githubusercontent.com/70861660/206313948-ea0561d0-430c-401b-b05d-7460ba341c64.png)
