### ISSUE TITLE
Criar lista de conteúdos que será utilizada

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#26]
#### Objetivo? 
Ter uma lista de conteúdos de alguma matéria para colocarmos no banco de dados.

#### Qual o problema?
Tendo uma lista de conteúdo bem estruturada dentro do banco de dados vamos conseguir iniciar o processo de envio de conteúdo sem precisar se preocupar com o conteúdo que será enviado

#### Tarefas 
- [x] Decidir qual conteúdo será utilizada em nosso bot
- [x] Colocar o conteúdo dentro da nossa [planilha](https://docs.google.com/spreadsheets/d/1jVvoIVlAb5VJY2IeQR-P-RreCehKb9wYKi6PsDJkLXA/edit#gid=2042367433)

#### Comentários 
---------------

**Comment by manuziny** [comment]
> A planilha foi preenchida com conteúdos de Cálculo 1, coloquei na ordem em que o conteúdo irá progredir.

**Comment by manuziny** [comment]
[Planilha](https://docs.google.com/spreadsheets/d/1jVvoIVlAb5VJY2IeQR-P-RreCehKb9wYKi6PsDJkLXA/edit?usp=sharing) preenchida com os conteúdos de Cálculo 1.
* Preenchi com de acordo com a progressão do conteúdo;
* Alguns com mais de um link;
* O código de verificação eu coloquei como se fosse no menu, assim vai indo de forma crescente;
