### ISSUE TITLE
Issue 2 → Pesquisa de ferramentas a serem utilizada

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#3]
#### Objetivo
Pesquisar ferramentas que poderão ser utilizadas para a criação de um bot.

#### Tarefas 
- [x] Pesquisar como funciona um bot no Telegram;
- [x] Pesquisar primeiros passos para a criação de um bot;
- [x] Implementar os primeiros passos se possível;
- [x] Listar quais são as principais ferramentas que possivelmente a serão utilizadas;
- [x] Documento de estudo para os outros membros do grupo.

#### Comentários 
---------------

**Comment by leonardogonmac** [comment]
### Tutorial de como criar um bot no telegram

Linguagem: Python;

1. [Tutorial 1 (PyCharm e em português);](https://www.youtube.com/watch?v=_RQw5Nw7Op0)
2. [Tutorial 2 (PyCharm e em inglês);](https://www.youtube.com/watch?v=PTAkiukJK7E)
3. [Tutorial 3 (VSCode e em inglês).](https://www.youtube.com/watch?v=RD3SyYHDQpo)

Obs: não sei se no VSCode precisa do comando `pip install python-telegram-bot` no terminal para importar a biblioteca que usar o bot do telegram, ou se tem uma extensão do próprio VSCode que dá essa biblioteca.  

Cada vídeo traz uma abordagem um pouco diferente de como criar os comandos do bot. Assim que puder, eu crio um exemplo e mando os códigos nessa issue.
Achei que ia ser bem mais difícil gerar um bot, mas parece até simples criar um exemplo.

**Comment by anafernanndess** [comment]
**_Documento de estudo para os outros membros do grupo._**

1. _Como Criar Bot no Python_ https://www.hashtagtreinamentos.com/bot-de-telegram-com-python#:~:text=Como%20Criar%20Bot%20no%20Python,possamos%20criar%20o%20nosso%20Bot.
2. _Download PyCharm Windows e Linux_ https://www.jetbrains.com/pt-br/pycharm/download/#section=windows ou https://www.jetbrains.com/pt-br/pycharm/download/#section=linux
3. _Download VSCode:_ https://code.visualstudio.com
4. _Para ter acesso gratis ao PyCharm PRO_: https://www.jetbrains.com/pt-br/community/education/#students
5. _O que é um bot e pra que serve:_ https://www.hardware.com.br/artigos/o-que-sao-bots-do-telegram/

**Comment by TalesRG** [comment]
**Complemento: Documento de estudo para os outros membros do grupo.**
1. Python : https://www.python.org/downloads/
2. Material sobre Python: [curso-python-versao-1.1.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/10027159/curso-python-versao-1.1.pdf)
