### ISSUE TITLE
Comando /contatosProfessor

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#34]
#### Objetivo? 
O aluno ter acesso aos meios de contado com o professor. 

#### Qual o problema a ser resolvido?
O aluno terá acesso aos contatos do professor de forma mais simples.

#### Tarefas // Critérios de aceitação
- [x] Criar o comando que envie os contatos
- [x] Criar um contatos falsos para utilizar no comando

#### Comentários 
---------------

**Comment by ananorberto** [comment]
@Beatrizvn 

Estou fazendo essa Issue hoje, quer que eu coloque para o bot enviar a mensagem para o professor caso o código digitado seja válido? #23

**Comment by ananorberto** [comment]
Ok! Era isso que eu estava pensando mesmo.

**Comment by Beatrizvn** [comment]
@ananorberto Para você se basear: [Aluno - Figma](https://www.figma.com/proto/jg8uxpnOEyLobSwp0HvG3e/Telegram-prototipo?node-id=35%3A4&scaling=min-zoom&page-id=0%3A3506&starting-point-node-id=35%3A4&show-proto-sidebar=1) passa pro lado até chegar no /contatosProfessor.
