### ISSUE TITLE
Preencher todos os requisitos do Community Standards do github

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#35]
#### Objetivo? 
Preencher todos os requisitos do Community Standars do github

#### Qual o problema a ser resolvido?
Para a release 1 do trabalho precisamos está com todos os requisitos do Community Standars preenchidos

#### Tarefas // Critérios de aceitação
- [x] Description
- [x] README
- [x] Code of conduct 
- [x] Contributing
- [x] License
- [x] Security policy 
- [x] Issue templates 
- [x] Pull request template 
- [x] Repository admins accept content reports 

#### Comentários 
---------------

**Comment by manuziny** [comment]
Todos os requistos do Community Standars foram preenchidos conforme o solicitado.
