### ISSUE TITLE
Protótipo no Figma 

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#36]
#### Objetivo? 
Criação do protótipo do produto no figma para facilitar a visualização do conceito e funcionalidades do bot.

#### Qual o problema a ser resolvido?
O protótipo vai facilitar a visualização dos participantes do grupo e da professora na apresentação na release 1.

#### Tarefas // Requisitos de Aceitação
- [x] Criação do protótipo com maior parte das funcionalidade que gostariamos de implementar
- [x] Colocar o protótipo no github

#### Comentários 
---------------

**Comment by Mylena-angelica** [comment]
O protótipo no figma será feito no link: [BOTO](https://www.figma.com/file/jg8uxpnOEyLobSwp0HvG3e/Telegram-prototipo?node-id=0%3A3506&t=zeJWV1XoG4wdWjPt-1)

**Comment by Mylena-angelica** [comment]
Flow do aluno feita : [Veja aqui](https://www.figma.com/proto/jg8uxpnOEyLobSwp0HvG3e/Telegram-prototipo?node-id=35%3A4&scaling=min-zoom&page-id=0%3A3506&starting-point-node-id=35%3A4)

Por favor, @Beatrizvn validar as informações

**Comment by Beatrizvn** [comment]
@Mylena-angelica flow do aluno verificado. 
Está tudo correto.

**Comment by Mylena-angelica** [comment]
Flow do professor feita: [Veja aqui](https://www.figma.com/proto/jg8uxpnOEyLobSwp0HvG3e/Telegram-prototipo?node-id=44%3A118&scaling=min-zoom&page-id=0%3A3506&starting-point-node-id=44%3A420&show-proto-sidebar=1)

**Comment by Mylena-angelica** [comment]
Para colocar no repositório no Git, foi criado a branch "36-prótotipo-no-figma" e será criado um arquivo com os links

**Comment by Mylena-angelica** [comment]
Pull request enviado para revisão
