### ISSUE TITLE
Criar tabelas no mysql 

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#37]
#### Objetivo? 
Criar as tabelas aluno e de conteudo.

#### Qual o problema a ser resolvido?
Criação das tabelas aluno e conteudo para serem utilizadas em issues futuras

#### Tarefas // Requisitos de Aceitação
- [x] Tabela aluno
- [x] Tabela conteudo
- [x] Colocar as tabelas no github para todos terem acesso a estrutura delas

#### Comentários 
---------------

**Comment by anafernanndess** [comment]
Create DATABASE BOTO;
USE BOTO;


CREATE TABLE alunos(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
matricula INT(9) NOT NULL
);


CREATE TABLE conteudos(
id INT PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(70) NOT NULL,
link VARCHAR(100) NOT NULL,
link_extra VARCHAR(100)
);
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Números reais, naturais, inteiros, racionais e irracionais', 'https://www.todamateria.com.br/conjuntos-numericos/', null);
INSERT INTO conteudos(titulo, link, link_extra) VALUES  ('Funções, modo de representar funções', 'https://www.matematica.pt/util/resumos/definir-representar-funcao.php', null);
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Limite e continuidade', 'https://youtu.be/DkCHV5Kbx4o', 'https://youtu.be/DIzwGegP8YE'); 
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Derivada', 'https://youtu.be/cWBEMN75IMc', 'https://educacionalplenus.com.br/exercicios-resolvidos-sobre-derivadas/'); 
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Aplicação da derivada', 'https://youtu.be/cJsJdXL3GOM', null); 
INSERT INTO conteudos(titulo, link, link_extra) VALUES ('Integral', 'https://youtu.be/wkijt8-uxpY', null);
INSERT INTO conteudos(titulo, link, link_extra) VALUES  ('Técnica de integração', 'https://youtu.be/nWEYwzzKLe8', 'https://pt.slideshare.net/DiegoOliveira462/exerccios-resolvidos-aplicao-da-integral');
INSERT INTO conteudos(titulo, link, link_extra) VALUES  ('Aplicação da integral', 'https://youtu.be/PxMMtutKS8w', null);


CREATE TABLE conteudos_feitos(
id INT PRIMARY KEY AUTO_INCREMENT,
fk_idConteudo int,
fk_idAluno int
);
alter table conteudos_feitos
add foreign key(fk_idConteudo)
references conteudos(id);

alter table conteudos_feitos
add foreign key(fk_idAluno)
references alunos(id);


![image](https://user-images.githubusercontent.com/90392277/207196639-12f54d34-4f8c-4381-bc3d-2ededc60824e.png)
