### ISSUE TITLE
Pesquisar as tecnologias para a implementação da arquitetura

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#39]
#### Objetivo? 
Descobrir quais ferramentas e tecnologias podemos utilizar para implementar  a [arquitetura](https://github.com/fga-eps-mds/2022-2-Squad02/issues/22)

#### Qual o problema a ser resolvido?
Antes de começar a programar de qualquer jeito, será feito uma pesquisa para entendermos  a melhor forma de implementar a arquitetura.

#### Tarefas // Requisitos de Aceitação
- [x] Pesquisar as tecnologias para implementação da arquitetura
- [x] Colocar o resultado da pesquisa nos comentarios da issue
- [x] Testar as tecnologias

#### Comentários 
---------------

**Comment by TalesRG** [comment]
[Livro Python3.pdf](https://github.com/fga-eps-mds/2022-2-Squad02/files/10213862/Livro.Python3.pdf) - Capitulo 17
