### ISSUE TITLE
Criar o Bot

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#6]
#### Objetivo? 
Criar o bot utilizando o Bot Father.

#### Tarefas 
- [x] Criar o bot

**Comment by leonardogonmac** [comment]
[commit subindo o bot de teste](https://github.com/fga-eps-mds/2022-2-Squad02/commit/8f9d9052e814f09b98e7cc5abcfc9ef022e42e9e)
