### ISSUE TITLE
Criar as planilhas

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#7]
#### Objetivo? 
Criação e organização da planilha que será utilizadas para os conteúdos e a planilha com a listagem de alunos inscritos no bot.

#### Tarefas 
- [x] Planilha de conteúdos 
- [x] Planilha de alunos

#### Comentários 
As duas planilhas devem estar no mesmo arquivo, mas em páginas separadas.

**Comment by ananorberto** [comment]
#### Foi criada uma planilha com 2 páginas (uma para os *Alunos* e outra para os *Conteúdos*), com os seguintes tópicos:

- Planinha de Alunos

| NOME | MATRÍCULA | QTD DE CONTEÚDOS | ATIVIDADES JA FEITAS | % CONCLUÍDO |
|:----:|:---------:|:----------------:|:--------------------:|:-----------:|
|  ana |  1234567  |         3       |            2          |        67%     |
|  bia |  7891011  |                  |             0         |         0%    |
|  leo |  12131415 |                  |            1          |        33%     |

- Planilha Conteúdos

| TÍTULO | LINK | CODIGO DE CONFIRMAÇAO | DATA |
|:------:|:----:|:---------------------:|:----:|
| sprint |      |          123          |      |
|  issue |      |          456          |      |
| github |      |          789          |      |

>_**OBS: Os dados colocados são apenas exemplos.**_
#
A planilha de Conteúdos é vinculada com a de Alunos para que cada conteúdo adicionado aumente a coluna de 
`QTD DE CONTEÚDOS` automaticamente. Para isso, foi utilizada a função **COUNTUNIQUE** para fazer a contagem 
dos conteúdos e a função **IMPORTRANGE** para fazer o _link_ de uma planilha com a outra.
- Função contagem: `=COUNTUNIQUE(A2:A100)`, está declarada na coluna 'E' (que esta oculta) da página de conteúdos.

- Função de importar: `=IMPORTRANGE("1jVvoIVlAb5VJY2IeQR-P-RreCehKb9wYKi6PsDJkLXA"; "Conteúdos!E4")`

Além disso, foi feito um cálculo simples de porcentagem na coluna de `% CONCLUÍDO` utilizando a função: 
- `=D2/$C$2`, onde `D2` varia a cada linha.
#
## Para acessar a planilha clique [AQUI](https://docs.google.com/spreadsheets/d/1jVvoIVlAb5VJY2IeQR-P-RreCehKb9wYKi6PsDJkLXA/edit#gid=0).
