### ISSUE TITLE
Conexão entre uma Planilha Google/Excel com o Bot

### ISSUE THREAD

**Issue by Beatrizvn** [fga-eps-mds/2022-2-Squad02#8]
#### Objetivo? 
Descobrir como fazer uma conexão entre uma planilha do Google/Excel e um bot do Telegram. Pesquisar sobre a relação entre o google drive api e a atualização de planilhas.

#### Tarefas 
- [x] Pesquisar sobre o google drive api e sua relação com atualização de planilhas;
- [x] Saber fazer uma conexão entre a planilha e o bot;
- [x] Documentar a pesquisa.

#### Comentários 
Atualizar uma planilha  → google drive api → Recomendação que a professora deu na descrição do tema.

**Comment by Mylena-angelica** [comment]
### **Google drive API**
#### Opções

- [Drive API](https://developers.google.com/drive/api)
- [Drive Activity API](https://developers.google.com/drive/activity)
- [Drive Labels API](https://developers.google.com/drive/labels)
- [Google picker API](https://developers.google.com/drive/picker)

#### Tutorias de pessoas que já utilizaram

- [API DO GOOGLE SHEETS COM PYTHON](https://www.hashtagtreinamentos.com/api-do-google-sheets-com-python)
- [Google Sheets API com Python + Sql Server](https://imasters.com.br/apis-microsservicos/google-sheets-api-com-python-sql-server)
- [Bot Telegram com Google Sheets](https://www.tomasvasquez.com.br/forum/viewtopic.php?f=27&t=7949&sid=93a51b98868b69fa9db611a47ec53a34)

#### Vídeos no Youtube

- [Use o Telegram pra gravar e consultar dados em uma planilha](https://www.youtube.com/watch?v=MxNkW9ooBZs)
- [Como criar um Bot de Telegram com Planilha do Google](https://www.youtube.com/watch?v=NYg5iDCjTNg)

**Comment by manuziny** [comment]
Notas sobre as API's
- A configuração não é complicada, testei de acordo com[ esse tutorial](https://www.hashtagtreinamentos.com/api-do-google-sheets-com-python) e ele não foi complicado;
- Falta testar a conexão entre o bot e uma planilha;
- De acordo com os tutoriais não parece ser uma implementação difícil, mas cabe adequar ao que queremos fazer;
- Testar usar a API com o Sql server pode ser bom também.
